name: run-on-docker
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
     matrix:
      job: [0, 1, 2, 3, 4]
    # Docker image with Cypress pre-installed
    # https://github.com/cypress-io/cypress-docker-images/tree/master/included
    container: cypress/included:9.2.0
    steps:
      - uses: actions/checkout@v2
      - run: cd "Part 10" && npm install && npm run cy:record:parallel:qa --ci-build-id ${{ github.run_id }}
